=== morenes/infoArt-Server/conf/mapa.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.um.es/as" xmlns="http://www.um.es/as"
	elementFormDefault="qualified">
	
	<xs:element name="mapaXML">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:long"/>
				<xs:element name="place" type="xs:int"/>
				<xs:element name="width" type="xs:int"/>
				<xs:element name="height" type="xs:int"/>
				<xs:element name="NEAR" type="xs:int"/>
				<xs:element name="MOVE" type="xs:int"/>
				<xs:element name="MOVE2" type="xs:int"/>
				<xs:element name="FACTOR" type="xs:double"/>
				<xs:element name="MIN_BEA" type="xs:int"/>
				<xs:element name="CONF_ALG" type="xs:int"/>
				<xs:element name="ajuste" type="tipoAjuste"
					minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="beacon" type="tipoBeacon"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tipoBeacon">
		<xs:sequence>
			<xs:element name="id" type="xs:unsignedByte"/>
			<xs:element name="x" type="xs:int"/>
			<xs:element name="y" type="xs:int"/>
			<xs:element name="coef" type="tipoCoef"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tipoAjuste">
		<xs:sequence>
			<xs:element name="id" type="xs:int"/>
			<xs:element name="x" type="xs:int"/>
			<xs:element name="y" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tipoCoef">
		<xs:sequence>
			<xs:element name="c" type="xs:float"
			minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== morenes/infoArt-Server/conf/mapa1.xml
<?xml version="1.0" encoding="UTF-8"?>

<mapaXML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.um.es/as"
	xsi:schemaLocation="http://www.um.es/as mapa.xsd">
	<id>124</id>
	<place>3</place>
	<width>500</width>
	<height>177</height>
	<NEAR>25</NEAR>
	<MOVE>40</MOVE>
	<MOVE2>20</MOVE2>
	<FACTOR>0.8</FACTOR>
	<MIN_BEA>3</MIN_BEA>
	<CONF_ALG>1</CONF_ALG>
	<beacon>
		<id>1</id>
		<x>4</x>
		<y>52</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>2</id>
		<x>74</x>
		<y>52</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>3</id>
		<x>138</x>
		<y>52</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>4</id>
		<x>202</x>
		<y>52</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>5</id>
		<x>266</x>
		<y>52</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>6</id>
		<x>266</x>
		<y>76</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>7</id>
		<x>222</x>
		<y>96</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>8</id>
		<x>234</x>
		<y>148</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>9</id>
		<x>302</x>
		<y>148</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>10</id>
		<x>358</x>
		<y>148</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>11</id>
		<x>384</x>
		<y>72</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>12</id>
		<x>434</x>
		<y>52</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>13</id>
		<x>500</x>
		<y>72</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>14</id>
		<x>500</x>
		<y>152</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
	<beacon>
		<id>15</id>
		<x>438</x>
		<y>176</y>
		<coef>
			<c>0</c>
			<c>1</c>
		</coef>
	</beacon>
</mapaXML>

=== morenes/infoArt-Server/conf/mapa3.xml
<?xml version="1.0" encoding="UTF-8"?>

<mapaXML xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.um.es/as"
	xsi:schemaLocation="http://www.um.es/as mapa.xsd">
	<id>124</id>
	<place>3</place>
	<width>500</width>
	<height>177</height>
	<NEAR>30</NEAR>
	<MOVE>50</MOVE>
	<MOVE2>20</MOVE2>
	<FACTOR>0.9</FACTOR>
	<MIN_BEA>3</MIN_BEA>
	<CONF_ALG>1</CONF_ALG>
	<ajuste>
		<id>50</id>
		<x>8</x>
		<y>52</y>
	</ajuste>
	<ajuste>
		<id>56</id>
		<x>296</x>
		<y>52</y>
	</ajuste>
	<beacon>
		<id>1</id>
		<x>4</x>
		<y>52</y>
		<coef>
			<c>1.5445</c>
			<c>-1.4204</c>
			<c>1.1343</c>
			<c>-0.1792</c>
			<c>0.0096</c>
		</coef>
	</beacon>
	<beacon>
		<id>2</id>
		<x>74</x>
		<y>52</y>
		<coef>
			<c>0.84</c>
			<c>0.1276</c>
			<c>0.1375</c>
			<c>0.0264</c>
			<c>-0.0027</c>
		</coef>
	</beacon>
	<beacon>
		<id>3</id>
		<x>138</x>
		<y>52</y>
		<coef>
			<c>1.8456</c>
			<c>-1.8441</c>
			<c>1.1284</c>
			<c>-0.1365</c>
			<c>0.0056</c>
		</coef>
	</beacon>
	<beacon>
		<id>4</id>
		<x>202</x>
		<y>52</y>
		<coef>
			<c>1.7357</c>
			<c>-1.5885</c>
			<c>0.933</c>
			<c>-0.1322</c>
			<c>0.0066</c>
		</coef>
	</beacon>
	<beacon>
		<id>5</id>
		<x>266</x>
		<y>52</y>
		<coef>
			<c>1.8448</c>
			<c>-1.7072</c>
			<c>1.1693</c>
			<c>-0.1716</c>
			<c>0.008</c>
		</coef>
	</beacon>
	<beacon>
		<id>6</id>
		<x>266</x>
		<y>76</y>
		<coef>
			<c>-0.4732</c>
			<c>1.5914</c>
			<c>-0.1858</c>
			<c>0.0028</c>
			<c>0.0017</c>
		</coef>
	</beacon>
	<beacon>
		<id>7</id>
		<x>222</x>
		<y>96</y>
		<coef>
			<c>1.9487</c>
			<c>-1.8531</c>
			<c>0.9397</c>
			<c>-0.1061</c>
			<c>0.0039</c>
		</coef>
	</beacon>
	<beacon>
		<id>8</id>
		<x>234</x>
		<y>148</y>
		<coef>
			<c>0.0801</c>
			<c>2.8244</c>
			<c>-0.6411</c>
			<c>0.1269</c>
			<c>-0.007</c>
		</coef>
	</beacon>
	<beacon>
		<id>9</id>
		<x>302</x>
		<y>148</y>
		<coef>
			<c>-1.5777</c>
			<c>2.3883</c>
			<c>-0.2982</c>
			<c>0.0325</c>
			<c>-0.001</c>
		</coef>
	</beacon>
	<beacon>
		<id>10</id>
		<x>358</x>
		<y>148</y>
		<coef>
			<c>1.1008</c>
			<c>-0.5716</c>
			<c>0.5815</c>
			<c>-0.0728</c>
			<c>0.003</c>
		</coef>
	</beacon>
	<beacon>
		<id>11</id>
		<x>384</x>
		<y>72</y>
		<coef>
			<c>2.4477</c>
			<c>-2.5383</c>
			<c>1.3568</c>
			<c>-0.194</c>
			<c>0.0094</c>
		</coef>
	</beacon>
	<beacon>
		<id>12</id>
		<x>434</x>
		<y>52</y>
		<coef>
			<c>0.5861</c>
			<c>0.8779</c>
			<c>-0.043</c>
			<c>0.035</c>
			<c>-0.0019</c>
		</coef>
	</beacon>
	<beacon>
		<id>13</id>
		<x>500</x>
		<y>72</y>
		<coef>
			<c>-2.3366</c>
			<c>3.3764</c>
			<c>-0.2824</c>
			<c>-0.0364</c>
			<c>0.0058</c>
		</coef>
	</beacon>
	<beacon>
		<id>14</id>
		<x>500</x>
		<y>152</y>
		<coef>
			<c>1.499</c>
			<c>-1.4051</c>
			<c>1.027</c>
			<c>-0.1566</c>
			<c>0.0078</c>
		</coef>
	</beacon>
	<beacon>
		<id>15</id>
		<x>438</x>
		<y>176</y>
		<coef>
			<c>1.9985</c>
			<c>-2.2105</c>
			<c>1.3932</c>
			<c>-0.225</c>
			<c>0.0128</c>
		</coef>
	</beacon>
</mapaXML>
