=== morenes/infoArt-Server/src/model/clusterRes/clusterRes.xsd
<?xml version="1.0" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.um.es/as" xmlns="http://www.um.es/as"
	elementFormDefault="qualified">

	<xs:element name="Clusters">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="place" type="xs:int" />
				<xs:element name="pila_gastada" type="xs:int" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="pila_debil" type="xs:int" minOccurs="0"
					maxOccurs="unbounded" />

				<xs:element name="cluster" type="tipoCluster" maxOccurs="unbounded" />
				<xs:element name="member" type="tipoMember" maxOccurs="unbounded" />


			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="tipoCluster">
		<xs:sequence>
			<xs:element name="var" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="id" type="xs:int" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>
	<xs:complexType name="tipoMember">
		<xs:sequence>
			<xs:element name="cluster" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="id" type="xs:int" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>

</xs:schema>

=== morenes/infoArt-Server/src/model/clusterRes/clusterRes.xml
<?xml version="1.0" encoding="UTF-8"?>

<Clusters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.um.es/as"
	xsi:schemaLocation="http://www.um.es/as clusterRes.xsd">
	<place>3</place>
	<pila_gastada>10</pila_gastada>
	<pila_gastada>11</pila_gastada>
	<pila_debil>10</pila_debil>
	<cluster id="1">
		<var id="1">12.1</var>
		<var id="2">0.43</var>
	</cluster>
	<cluster id="2">
		<var id="1">12.1</var>
		<var id="2">0.43</var>
	</cluster>
	<member id="1">
		<cluster id="1">0.1</cluster>
		<cluster id="2">0.9</cluster>
	</member>
</Clusters>
